export const OBJECTIVES = [
  "Promote active engagement from local officials to support the development of start-up community in the region;",
  "Equip the Startups with knowledge on the programs and services of Agency Keyplayers and Technology Incubators;",
  "Pitch products or technologies to potential investors, technology adopters, and funding agencies;",
  "Inspire the startup community through sharing best practices and success stories of successful startups in the region; and",
  "Promote business networking and startup investing.",
];

export const DAY1 = [
  {
    time: "8:00 AM - 9:20 AM",
    title: "Opening Ceremony",
    speakers: [""],
    location: "Claude Andrews Convention Center",
    bg: "#2E57D0",
  },
  {
    time: "9:20 AM - 9:30 AM",
    title: "Welcome and Inspirational Message",
    speakers: [
      "Dr. Urdujah G. Alvarado, CSU President",
      "Hon. Maila Ting Que, Mayor, Tuguegarao City",
    ],
    location: "Claude Andrews Convention Center",
    bg: "#F3C71B",
  },
  {
    time: "9:30 AM - 9:45 AM",
    title: "Introduction to Overview of the Cagayan Valley Startup Week 2023",
    speakers: [""],
    location: "Claude Andrews Convention Center",
    bg: "#2E57D0",
  },
  {
    time: "10:15 AM - 10:35 AM",
    title: "Keynote Address",
    speakers: ["DICT Usec David L. Almirol"],
    location: "Claude Andrews Convention Center",
    bg: "#2E57D0",
  },
  {
    time: "10:40 AM - 11:00 AM",
    title: "Keynote Address",
    speakers: ["DTI Usec Rafaelita Aldaba"],
    location: "Claude Andrews Convention Center",
    bg: "#2E57D0",
  },
  {
    time: "11:20 AM - 11:30 AM",
    title: "Keynote Address",
    speakers: ["Hon. Joseph L. Lara"],
    location: "Claude Andrews Convention Center",
    bg: "#2E57D0",
  },
  {
    time: "11:30 AM - 12:00 AM",
    title: "Formal Opening of the Grand Exhibit",
    speakers: [""],
    location: "Claude Andrews Convention Center",
    bg: "#2E57D0",
  },
  {
    time: "1:15 PM - 1:45 PM",
    title: "MOA Signing with New SINAG Members",
    speakers: [""],
    location: "Claude Andrews Convention Center",
    bg: "#2E57D0",
  },
  {
    time: "2:15 PM - 2:45 PM",
    title: "Startup Success Stories",
    speakers: [""],
    location: "Claude Andrews Convention Center",
    bg: "#2E57D0",
  },
  {
    time: "2:50 PM - 3:30 PM",
    title: "Keynote Address",
    speakers: ["Dir. Enrico Paringit"],
    location: "Claude Andrews Convention Center",
    bg: "#2E57D0",
  },
  {
    time: "2:50 PM - 3:30 PM",
    title: "Investor Pitch",
    speakers: [""],
    location: "Claude Andrews Convention Center",
    bg: "#2E57D0",
  },
  {
    time: "5:00 PM - 8:00 PM",
    title: "Business Forum and Networking (TED Talks)",
    speakers: ["Dir. Enrico Paringit"],
    location: "Claude Andrews Convention Center",
    bg: "#2E57D0",  
  },
];
